name: ðŸ“ RootCA Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  rootca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: install update-rootcerts
        run: |
          go install github.com/projectdiscovery/tlsx/cmd/update-rootcerts

      - name: update root certificate changes
        id: cert
        run: |
          update-rootcerts -out-root-certs ./assets/root-certs.pem
        working-directory: .

      - name: create local changes
        run: |
          git add ./assets/root-certs.pem

      - name: check for local changes
        id: change
        run: |
          git diff --quiet && echo "No changes to commit" || echo "CHANGED=true" >> $GITHUB_ENV

      - name: Commit files
        if: steps.change.outputs.CHANGED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Weekly root certifacte update [$(date)] :robot:" -a --allow-empty

      - name: Push changes
        if: steps.change.outputs.CHANGED == 'true'
        run: |
          git pull --rebase
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}